owner: z-shell
repo: status
sites:
  - name: wiki.zshell.dev
    url: https://z-shell.pages.dev
  - name: ipfs.zshell.dev
    url: https://zi-src.on.fleek.co
  - name: init.zshell.dev
    url: https://init.zshell.dev
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 503
  - name: get.zshell.dev
    url: https://get.zshell.dev
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 503
  - name: git.io/get-zi
    url: https://git.io/get-zi
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
  - name: git.io/zi-loader
    url: https://git.io/zi-loader
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
  - name: cdn.digitalclouds.dev
    url: https://cdn.digitalclouds.dev/fa/js/all.js
  - name: RAW github.com
    url: https://raw.githubusercontent.com/z-shell/zi/main/docs/README.md
  - name: RAW gitlab.com
    url: https://gitlab.com/ss-o/zi/-/raw/main/docs/README.md
  - name: 1.1.1.1:53
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
    icon: https://www.cloudflare.com/favicon.ico
  - name: 8.8.8.8:53
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    icon: https://www.google.com/favicon.ico
  - name: Crowdin/Z-Shell
    url: https://crowdin.digitalclouds.dev/z-shell
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 503
  #- name: Secret Site
  #  url: $SECRET_SITE
  #- name: API endpoint
  #  url: https://example.com/get-user/3?api_key=$MY_API_KEY
  #- name: API endpoint
  #  url: https://example.com/get-user/3
  #  headers:
  #   - "Authorization: Bearer $SECRET_SITE_2"
  #   - "Content-Type: application/json"
  #- name: API endpoint with data
  #  method: POST
  #  url: https://example.com/login
  #  headers:
  #    - "Content-Type: application/json"
  #  body: '{ "password": "hello" }'
status-website:
  scripts:
    - src: https://github.zshell.dev/fa/js/all.min.js
      async: true
  links:
    - rel: stylesheet
      href: https://github.zshell.dev/fa/css/all.min.css
  themeUrl: https://status.zshell.dev/themes/night.css
  logoUrl: https://github.com/z-shell.png
  metaTags:
    - name: "robots"
      content: "noindex"
  # css: "body { opacity: 0.5 }"
  baseUrl: /
  theme: night
  cname: status.zshell.dev
  apiBaseUrl: https://api.github.com
  name: "Z-Shell ❮ ZI ❯"
  introTitle: "<i class='fa-solid fa-chart-line'> Uptime Status </i>"
  introMessage: "<i class='fa-brands fa-connectdevelop'></i> The open-source uptime monitor and status page for Z-Sehll."
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Contact
      href: https://github.zshell.dev
    - title: Z-Shell Organization
      href: https://github.com/$OWNER
# Customize the schedule when Uptime workflows run by adding the workflowSchedule key in your configuration file.
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
# Commits to git history to keep a track of response times, and also commits graphs and README updates.
commitMessages:
  commitAuthorName: "digital-teams[Bot]"
  commitAuthorEmail: "digital-teams@pm.me"
user-agent: digital-teams
assignees:
  - jwdevelab
# See https://upptime.js.org/docs/configuration
