owner: z-shell
repo: status
user-agent: ss-o
sites:
  - name: ZI Wiki [URL]
    url: https://z-shell.pages.dev
  - name: ZI Source IPFS [URL]
    url: https://zi-src.on.fleek.co
  - name: ZI Content Delivery [URL]
    url: https://cdn.digitalclouds.dev/fa/js/all.js
  - name: Redirect i-hub [URL]
    url: https://z-shell.pages.dev/i-hub
  - name: Redirect i-lab [URL]
    url: https://z-shell.pages.dev/i-lab
  - name: Redirect i-tee [URL]
    url: https://z-shell.pages.dev/i-tee
  - name: Gitee SSH [TCP 22]
    check: "tcp-ping"
    url: gitee.com
    port: 22
  - name: Gitee RAW [URL]
    url: https://gitee.com/z-shell/zi-src/raw/main/lib/sh/install.sh
  - name: Github SSH [TCP 22]
    check: "tcp-ping"
    url: github.com
    port: 22
  - name: GitHub RAW [URL]
    url: https://raw.githubusercontent.com/z-shell/zi/main/docs/README.md
  - name: GitLab SSH [TCP 22]
    check: "tcp-ping"
    url: gitlab.com
    port: 22
  - name: GitLab RAW [URL]
    url: https://gitlab.com/ss-o/zi/-/raw/main/docs/README.md
  - name: Cloudlfare DNS [TCP 53]
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: Google DNS [TCP 53]
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: Crowdin [STATUS CODE]
    url: https://crowdin.digitalclouds.dev/z-shell
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 503
status-website:
  scripts:
    - src: https://cdn.digitalclouds.dev/fa/js/all.min.js
      async: true
  links:
    - rel: stylesheet
      href: https://cdn.digitalclouds.dev/fa/css/all.min.css
  themeUrl: https://status.zshell.dev/themes/night.css
  logoUrl: https://github.com/z-shell.png
  baseUrl: /
  theme: night
  cname: status.zshell.dev
  name: "Z-Shell ❮ ZI ❯"
  introTitle: "<i class='fa-solid fa-chart-line'></i> Uptime Status"
  introMessage: "<i class='fa-brands fa-connectdevelop'></i> The resources which have an influence on the Z-Shell performance."
  commitMessages:
    readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
    summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
    statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
    graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
    commitAuthorName: "digital-teams[Bot]"
    commitAuthorEmail: "digital-teams@pm.me"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Contact
      href: https://github.com/$OWNER
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
commitMessages:
  commitAuthorName: "digital-teams[bot]"
  commitAuthorEmail: "digital-teams@pm.me"
# See https://upptime.js.org/docs/configuration
