owner: z-shell
repo: status
sites:
  - name: ZW Cloudflare
    url: https://z-shell.pages.dev
  - name: ZI Source IPFS    
    url: https://zi-src.on.fleek.co
  - name: Z-Shell Crowdin
    url: https://digitalclouds.crowdin.com/z-shell
  - name: Cloudlfare Redirect 1
    url: https://z-shell.pages.dev/i-hub
  - name: Cloudlfare Redirect 2
    url: https://z-shell.pages.dev/i-lab
  - name: Cloudlfare Redirect 3
    url: https://z-shell.pages.dev/i-tee    
  - name: Gitee (SSH)
    check: "tcp-ping"
    url: gitee.com
    port: 22
  - name: Gitee (RAW)
    url: https://gitee.com/z-shell/zi-src/raw/main/lib/sh/install.sh
  - name: Github (SSH)
    check: "tcp-ping"
    url: github.com
    port: 22
  - name: GitHub (RAW)
    url: https://raw.githubusercontent.com/z-shell/zi/main/docs/README.md
  - name: GitLab (SSH)
    check: "tcp-ping"
    url: gitlab.com
    port: 22
  - name: GitLab (RAW)
    url: https://gitlab.com/ss-o/zi/-/raw/main/docs/README.md
  - name: Cloudlfare DNS
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: Google DNS
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    
status-website:
  theme: dark
  cname: status.zshell.dev
  #baseUrl: /status
  logoUrl: https://github.com/z-shell.png
  name: ❮ ZI ❯
  introTitle: "Z-Shell Status"
  introMessage: " The resources which have an influence on the Z-Shell performance."
  commitMessages:
    readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
    summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
    statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
    graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
    commitAuthorName: "digital-teams[Bot]"
    commitAuthorEmail: "digital-teams@pm.me"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Contact
      href: https://github.com/$OWNER
# See https://upptime.js.org/docs/configuration
