extends: default

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true
  line-length: disable
  quoted-strings: disable
  truthy:
    allowed-values: ["true", "false", "on"]
